New C, CPP, SQLC and SQLCPP object types plus multiple compile options
IBM/bob-recursive-example pull request #2
Opened 2023-04-18 18:38 UTC by sbestgen

Adding new types plus compiles that specify more than one compile option to process. Edmund, I've tested this on my system but it might be worth trying on another box as well?

2023-04-18 21:08 UTC, edmundreinhardt requested changes

2023-04-18 21:08 UTC, edmundreinhardt commented on QCPPSRC/Rules.mk
> +PGMs :=  PWD.PGM
Don't need these 2 lines any more

2023-04-18 21:08 UTC, edmundreinhardt commented on QCSRC/Rules.mk
> +MODULEs := PUTIFSCHK.MODULE
drop top 2 lines (MODULES and PGMS)

2023-04-18 21:08 UTC, edmundreinhardt commented on QSQLCPPSRC/Rules.mk
> +MODULEs := ANZ_FILE.MODULE
drop MODULEs PGMs

2023-04-18 21:08 UTC, edmundreinhardt commented on QSQLCSRC/Rules.mk
> +MODULEs := ANZ_FILE2.MODULE
drop MODULEs PGMs

2023-04-19 16:53 UTC, sbestgen commented on QCPPSRC/Rules.mk
> +PGMs :=  PWD.PGM
New code committed.

2023-04-19 16:53 UTC, sbestgen commented on QCSRC/Rules.mk
> +MODULEs := PUTIFSCHK.MODULE
New code committed.

2023-04-19 16:53 UTC, sbestgen commented on QSQLCPPSRC/Rules.mk
> +MODULEs := ANZ_FILE.MODULE
New code committed.

2023-04-19 16:53 UTC, sbestgen commented on QSQLCSRC/Rules.mk
> +MODULEs := ANZ_FILE2.MODULE
New code committed.

2023-04-19 17:27 UTC, merged